services:
  prevdent-app:
    build: .
    container_name: prevdent-app
    ports:
      - "8126:8126"
    env_file:
      - .env
    environment:
      - DD_SERVICE=prevdent-java-mvc
      - DD_ENV=dev
      - DD_VERSION=1.0.0
      - DD_LOGS_INJECTION=true
      - DD_TRACE_ENABLED=true
      - DD_AGENT_HOST=dd-agent
      - DD_TRACE_AGENT_PORT=8126
    depends_on:
      - dd-agent

  dd-agent:
    image: gcr.io/datadoghq/agent:7
    container_name: dd-agent
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=us5.datadoghq.com
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_CONTAINER_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro

