spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: keven
    password: keven123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

api:
  security:
    jwt:
      secret: your_secret_key_here


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"


  metrics:
    export:
      datadog:
        enabled: true
        api-key: ${DD_API_KEY}
        step: 30s

datadog:
  api-key: ${DD_API_KEY}
  site: us5.datadoghq.com
  tracing:
    enabled: true
  logs:
    enabled: true
    container-logs:
      enabled: true
  apm:
    enabled: true

dd:
  service: prevdent-java-mvc
  env: dev
  version: 1.0.0