spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
    username: "RM553621"
    password: "051102"
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: create

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest

api:
  security:
    jwt:
      secret: your_secret_key_here


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8081

management:
  tracing:
    enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  datadog:
    metrics:
      export:
        enabled: true
        apiKey: fef011710a3fe9e7eb5e395446112c37
        step: 30s