spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
    username: "RM553621"
    password: "051102"
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create

api:
  security:
    jwt:
      secret: your_secret_key_here


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8081