spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: keven
    password: keven123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest


api:
  security:
    jwt:
      secret: your_secret_key_here


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8081

management:
  tracing:
    enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  datadog:
    metrics:
      export:
        enabled: true
        apiKey: 4f9a6471c8543cd56eddd10a6157dfc2
        step: 30s






